openapi: 3.0.0

info:
  version: 0.0.1
  title: Library Service
  description: The library service

tags:
  - name: "Library"

paths:
  /library/books:
    get:
      summary: This is a summary
      tags:
        - "Library"
      description: This is a description
      operationId: getAllBooksInLibrary
      responses:
        "200":
          description: This means its ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

components:
  schemas:
    Book:
      description: This is a book model
      type: object
      properties:
        name:
          description: The name of the book
          type: string
        bookAuthor:
          description: The name of the author
          type: string
